name: test

on:
  push:
    branches: [master]
  
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    
    steps: 
     - name: Clonando repositorio
       uses: actions/checkout@v2
     
     - name: Configurando ambiente Python
       uses: actions/setup-python@v2
       with: 
        python-version: 3.8
        
     - name: Instalando dependencias
       run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
     - name: Iniciando banco
       uses: supercharge/mongodb-github-action@1.3.0
       with:
        mongodb-version: 4.0
  
     - name: Executando testes
       run: |
        cd user_crud
        pytest
